
[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/Masterminds/squirrel"
  version = "^1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "^2.2.1"

[prune]
  go-tests = true
  unused-packages = true
